spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comment: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace