spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/study_planner_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: p@ssw0rd
    platform: dev
    initialization-mode: always
