spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comment: true
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace